apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxtest
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.7.1
    chart: nginx
    helm:
      valueFiles:
        - https://github.com/We-Solve-For-X/argo-test/blob/main/nginx/values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
